# Generated by Django 3.2.12 on 2023-04-17 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=62)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=150)),
                ('basket_history', models.JSONField(default=dict)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[('Создан', 0), ('Оплачен', 1), ('В пути', 2), ('Доставлен', 3)], default=0)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
